---
title: "Lothian Pension Fund Investments in Fossil Fuels"
author: "Divest Lothian"
date: "5 October 2016"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(tidyr)
library(ggplot2)

knitr::opts_chunk$set(echo = TRUE, fig.align="center")

load("data/lpf.Rdata")
lpf_coal <- filter(lpf, coal == "Yes")
lpf_oil_gas <- filter(lpf, oil_gas == "Yes")
lpf_fossil_fuel <- filter(lpf, fossil_fuel == "Yes")

```

# Size of fund by year

This section shows how the value of fossil fuels as a proportion of the value of the fund has declined in recent years.

```{r fund_size}

fund_size <- aggregate(formula = market_value ~ date, data = lpf,  FUN = sum) %>% rename(Total = market_value)

coal_size <- aggregate(formula = market_value ~ date, data = lpf_coal, FUN = sum) %>% rename(Coal = market_value)

oil_gas_size <- aggregate(formula = market_value ~ date, data = lpf_oil_gas, FUN = sum) %>% rename(`Oil and Gas` = market_value)

fossil_fuel_size <- aggregate(formula = market_value ~ date, data = lpf_fossil_fuel, FUN = sum) %>% rename(`All Fossil Fuels` = market_value)

table <- left_join(fund_size, coal_size, by = "date") %>%
  left_join(oil_gas_size, by = "date") %>%
  left_join(fossil_fuel_size, by = "date") %>% 
  mutate(`Coal %` = round((Coal/Total)*100, 1)) %>% 
  mutate(`Oil and Gas %` = round((`Oil and Gas`/Total)*100, 1)) %>% 
  mutate(`Fossil Fuel %` = round((`All Fossil Fuels`/Total)*100, 1))

plot_table <- gather(table, investment_group, value,  Coal:`All Fossil Fuels`)

ggplot(data = plot_table, aes(x = date, y = value, colour = investment_group)) +
  geom_point() +
  geom_line(aes(group = investment_group)) +
  ggtitle("How the value of Lothan Pension Fund Fossil Fuel Investments are falling")

kable(table, format.args = list(big.mark = ","))

rm(fund_size, coal_size, oil_gas_size, fossil_fuel_size, table, plot_table)
```
# A closer look at particular investments

This section looks at the particular investments the fund has in fossil fuels. It shows that the value of particular investments has fallen, in some cases quite significantly.

```{r particular investments}

holdings <- function(data, d){
  table <- filter(data, date == d, fossil_fuel == 'Yes') %>% 
  select(asset_name, holding, market_value, holding_value, date)
  
  names(table) <- c("asset_name",
                   paste(d, "holding"),
                   paste(d, "market_value"),
                   paste(d, "holdng_value"))
  
  table
}

ff2014 <- holdings(lpf, d = "2014-03-31")
ff2015 <- holdings(lpf, d = "2015-03-31")
ff2016 <- holdings(lpf, d = "2016-03-31")

ff <- left_join(ff2014, ff2015, by = "asset_name") %>% 
  left_join(ff2016, by = "asset_name")

```